import { CERTIFICATION, TERMS_VERSION } from "@/lib/manufacturing-contract"
export default function TermsPage() {
  return <article className="mx-auto max-w-3xl space-y-6 px-5 py-12 leading-8"><h1 className="text-4xl font-bold">Manufacturing API terms</h1><p>Version {TERMS_VERSION} · TCGPlaytest / Cardify LLC</p>
    <h2 className="text-2xl font-bold">Client-supplied content</h2><p>The client selects, hosts, or supplies every artwork file, including card fronts and backs, and is solely responsible for intellectual-property rights in that content. The client must own or have permission to reproduce all submitted content and must obtain any necessary authorization from its customers. The client submits files and manufacturing instructions only in connection with a customer order.</p>
    <h2 className="text-2xl font-bold">Certification on every order</h2><ul className="list-disc pl-6">{Object.values(CERTIFICATION).map(text=><li key={text}>{text}</li>)}</ul><p>Submitting an API cart records these certifications, the authenticated client, the API key identifier, the terms version, file hashes, and submission time. These certifications accompany the paid manufacturing order.</p>
    <h2 className="text-2xl font-bold">Limited manufacturing role</h2><p>TCGPlaytest receives client-supplied files solely to execute manufacturing and fulfillment instructions. TCGPlaytest does not supply, sell, curate, license, authenticate, endorse, or verify intellectual-property rights in submitted content. It does not provide an image library, choose or substitute artwork, or make substantive creative decisions. The client authorizes only the processing needed for production and fulfillment, including resizing, cropping, bleed generation, color conversion, preflighting, imposition, and RIP/print preparation.</p>
    <h2 className="text-2xl font-bold">Retention</h2><p>Artwork is temporarily stored in private production storage. Files are scheduled for deletion after their operational retention period, normally 30 days following shipment or cancellation. Unpaid carts expire after seven days; source URLs are removed after a 24-hour grace period for an already-open payment session. Troubleshooting or legally required preservation may extend retention with a recorded reason. Client and order metadata, timestamps, certifications, hashes, and production/deletion records may be retained. Deleted artwork is not available for future reorders; a new submission is required.</p>
    <h2 className="text-2xl font-bold">Responsibility and indemnification</h2><p>The client agrees to indemnify and hold harmless TCGPlaytest, Cardify LLC, and their officers, employees, and agents from claims, damages, liabilities, and reasonable expenses, including reasonable attorneys’ fees, arising from content submitted by the client or its customers, alleged infringement of third-party rights in that content, or breach of these certifications, to the extent permitted by applicable law.</p>
    <h2 className="text-2xl font-bold">Enforcement and copyright complaints</h2><p>TCGPlaytest may hold, block, decline, or cancel an order, artwork file, client, or API account when infringement is reported or becomes specifically known. Repeat infringers may have their access terminated in appropriate circumstances. Notices and counter-notices are reviewed through the copyright complaint process. Submission of a counter-notice does not itself authorize printing to resume. Payment refunds and physical-production stoppage are reviewed separately.</p>
    <h2 className="text-2xl font-bold">API and checkout</h2><p>Keys must remain on the client’s server. Test carts are never charged, printed, or shipped. Live customers pay TCGPlaytest’s standard manufacturing rates. Affiliate discounts and rewards remain subject to the existing TCGPlaytest checkout rules. Partners may not claim an official, endorsed, or exclusive relationship without written agreement.</p>
  </article>
}
