import { CUSTOMER_RIGHTS_STATEMENT, PARTNER_TERMS_STATEMENT, TERMS_VERSION } from "@/lib/manufacturing-contract"
export default function TermsPage() {
  return <article className="mx-auto max-w-3xl space-y-6 px-5 py-12 leading-8"><h1 className="text-3xl font-bold sm:text-4xl">Manufacturing API terms</h1><p>Version {TERMS_VERSION} · TCGPlaytest / Cardify LLC</p>
    <h2 className="text-2xl font-bold">Partner content and complaint obligations</h2><p>{PARTNER_TERMS_STATEMENT}</p>
    <h2 className="text-2xl font-bold">Client-supplied content</h2><p>The partner's website selects, hosts, or supplies every artwork file, including card fronts and backs. The partner submits files and manufacturing instructions in connection with a customer order. Accept these partner terms once per version in the dashboard; the accepted version and timestamp are recorded server-side on every new cart. The API does not accept a per-request rights certification from the partner.</p>
    <h2 className="text-2xl font-bold">Customer image-rights certification</h2><p>Before payment, the customer must check the following statement at checkout:</p><blockquote className="border-l-2 border-cyan-300 pl-4">{CUSTOMER_RIGHTS_STATEMENT}</blockquote><p>TCGPlaytest records the cart ID, customer acceptance timestamp, statement and terms version, authenticated partner, API key identifier, computed file hashes, and submission time. The customer's certification does not replace the partner's obligations above. Technical file validation does not verify reproduction rights.</p>
    <h2 className="text-2xl font-bold">Limited manufacturing role</h2><p>TCGPlaytest receives client-supplied files solely to execute manufacturing and fulfillment instructions. TCGPlaytest does not supply, sell, curate, license, authenticate, endorse, or verify intellectual-property rights in submitted content. It does not provide an image library, choose or substitute artwork, or make substantive creative decisions. The client authorizes only the processing needed for production and fulfillment, including resizing, cropping, bleed generation, color conversion, preflighting, imposition, and RIP/print preparation.</p>
    <h2 className="text-2xl font-bold">Retention</h2><p>Artwork is temporarily stored in private production storage. Files are scheduled for deletion after their operational retention period, using the configured retention period following shipment or cancellation. Unpaid carts expire at their recorded expiry time and are queued for file deletion. Existing payment attempts are reconciled first to avoid deleting files for a paid order whose payment notification is delayed. Failed validation carts are also queued for deletion. Files are not reused across carts. Troubleshooting or legally required preservation may extend retention with a recorded reason. Client and order metadata, timestamps, certifications, hashes, and production/deletion records may be retained. Deleted artwork is not available for future reorders; a new submission is required.</p>
    <h2 className="text-2xl font-bold">Responsibility and indemnification</h2><p>The partner agrees to indemnify and hold harmless TCGPlaytest, Cardify LLC, and their officers, employees, and agents from claims, damages, liabilities, and reasonable expenses, including reasonable attorneys’ fees, arising from the partner's breach of the content and complaint-handling obligations in these terms, to the extent permitted by applicable law.</p>
    <h2 className="text-2xl font-bold">Enforcement and copyright complaints</h2><p>TCGPlaytest may hold, block, decline, or cancel an order, artwork file, client, or API account when infringement is reported or becomes specifically known. Repeat infringers may have their access terminated in appropriate circumstances. Notices and counter-notices are reviewed through the copyright complaint process. Submission of a counter-notice does not itself authorize printing to resume. Payment refunds and physical-production stoppage are reviewed separately.</p>
    <h2 className="text-2xl font-bold">API and checkout</h2><p>Keys must remain on the client’s server. Test carts are never charged, printed, or shipped. Live customers pay TCGPlaytest’s standard manufacturing rates. Affiliate discounts and rewards remain subject to the existing TCGPlaytest checkout rules. Partners may not claim an official, endorsed, or exclusive relationship without written agreement.</p>
  </article>
}
